hsp1:
    policy_config_path: random3_m/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    algo: HSP
    model_path:
        actor: random3_m/hsp/s2/hsp_plate-S2-s24/1.pt
hsp2:
    policy_config_path: random3_m/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    algo: HSP
    model_path:
        actor: random3_m/hsp/s2/hsp_plate-S2-s24/2.pt
hsp3:
    policy_config_path: random3_m/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    algo: HSP
    model_path:
        actor: random3_m/hsp/s2/hsp_plate-S2-s24/3.pt

mep1:
    policy_config_path: random3_m/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    algo: MEP
    model_path:
        actor: random3_m/mep/s2/mep-S2-s24/1.pt
mep2:
    policy_config_path: random3_m/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    algo: MEP
    model_path:
        actor: random3_m/mep/s2/mep-S2-s24/2.pt
mep3:
    policy_config_path: random3_m/policy_config/rnn_policy_config.pkl
    featurize_type: ppo
    algo: MEP
    model_path:
        actor: random3_m/mep/s2/mep-S2-s24/3.pt

e3t1:
    policy_config_path: random3_m/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    algo: E3T
    model_path:
        actor: random3_m/e3t/s1/e3t/1.pt
e3t2:
    policy_config_path: random3_m/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    algo: E3T
    model_path:
        actor: random3_m/e3t/s1/e3t/2.pt
e3t3:
    policy_config_path: random3_m/policy_config/mlp_policy_config.pkl
    featurize_type: ppo
    algo: E3T
    model_path:
        actor: random3_m/e3t/s1/e3t/3.pt 